# Generated by Django 5.2.14 on 2026-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolenoidControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ON', 'Manual ON'), ('OFF', 'Manual OFF'), ('AUTO', 'Auto Timer')], default='AUTO', max_length=10)),
                ('energized_time', models.PositiveIntegerField(default=1800)),
                ('deenergized_time', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
