# Generated by Django 5.2.14 on 2026-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solenoidcontrol',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
