# Generated by Django 5.2.14 on 2026-05-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationApp', '0002_solenoidcontrol_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solenoidcontrol',
            name='deenergized_time',
        ),
        migrations.RemoveField(
            model_name='solenoidcontrol',
            name='energized_time',
        ),
        migrations.RemoveField(
            model_name='solenoidcontrol',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='solenoidcontrol',
            name='auto_closed_time',
            field=models.PositiveIntegerField(default=18000),
        ),
        migrations.AddField(
            model_name='solenoidcontrol',
            name='auto_open_time',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='solenoidcontrol',
            name='manual_afternoon_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='solenoidcontrol',
            name='manual_closed_time',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='solenoidcontrol',
            name='manual_morning_time',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AddField(
            model_name='solenoidcontrol',
            name='manual_open_time',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='solenoidcontrol',
            name='mode',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual Timer'), ('ON', 'Force Open - Debug'), ('OFF', 'Force Close - Debug')], default='AUTO', max_length=10),
        ),
    ]
